apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "static-website.fullname" . }}
  labels:
    {{- include "static-website.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "static-website.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "static-website.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: SECRET_VALUE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: secret-value
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}